export const tabAlbums = [
  '序号',
  '锁定',
  '修改记录',
  '专辑UID',
  '资源权限',
  '专辑名',
  '激活日期',
  '封面',
  '宽封面',
  '定时推送',
  '每日必听',
  '专辑分类',
  '供应商',
  '供应商状态',
  '供应商权限',
  '年龄',
  '下架音频',
  '播放次数',
  '供应商播放次数',
  '音轨数',
  '收藏数',
  '主播名',
  '宝宝ID',
  '家庭ID',
  '禁止分享',
  '分享链接',
  '链接有效',
  '链接有效时间',
  '音量',
  '文章ID',
  '转采源',
  '简介',
  '更新时间',
  '创建时间'
]

export const tabAlbumsExcel = [
  ['index', '序号'],
  ['uid', '专辑Uid'],
  ['name', '专辑名'],
  ['coverUrl', '封面'],
  ['refreshEveryday', '每日推送'],
  ['categoryIds', '专辑分类'],
  ['vendor', '供应商'],
  ['vendorState', '供应商状态'],
  ['ageShow', '年龄'],
  ['bannedTracksCnt', '下架音频'],
  ['playCnt', '播放次数'],
  ['vendorPlayCnt', '供应商播放次数'],
  ['tracksCnt', '音轨数'],
  ['likeCnt', '收藏数'],
  ['announcerName', '主播名'],
  ['deviceId', '宝宝ID'],
  ['familyId', '家庭ID'],
  ['noShare', '禁止分享'],
  ['shareStatusShared', '分享链接'],
  ['shareStatusValid', '链接有效'],
  ['volume', '音量'],
  ['shadowOf', '转采源'],
  ['info', '简介'],
  ['update', '更新时间'],
  ['created', '创建时间']
]
// export const tabAlbumsExcel = [
//   ['uid', '专辑Uid'],
//   ['access','资源权限'],
//   'name',
//   'coverUrl',
//   'refreshEveryday',
//   'categoryIds',
//   'vendor',
//   'vendorState',
//   'bannedTracksCnt',
//   'playCnt',
//   'vendorPlayCnt',
//   'tracksCnt',
//   'likeCnt',
//   'announcerName',
//   'deviceId',
//   'familyId',
//   'noShare',
//   'shareStatus.shared',
//   'shareStatus.linkValid',
//   'volume',
//   'shadowOf',
//   'info',
//   'update',
//   'created'
// ]

export const tabAlbumsCategory = [
  '序号',
  '锁定',
  '修改记录',
  '专辑分类ID',
  '资源权限',
  '分类排序',
  '分组编号',
  '分组名',
  '分类图标',
  '推荐图标',
  '推荐排序',
  '专辑分类名',
  '年龄',
  '专辑数',
  '音频数',
  '下架音频'
]

export const tabPost = [
  '序号',
  '页面UID',
  '页面标题',
  '所在目录',
  '操作',
  '分享链接',
  '评论数',
  '允许评论',
  '阅读用户数',
  '阅读数',
  '状态',
  '修改记录',
  '更新时间',
  '创建时间'
]
