export const vendor = [
  { cn: '正常', name: 'normal' },
  { cn: '已删除', name: 'deleted' },
  { cn: '下架', name: 'banned' },
  { cn: '内部', name: 'internal' },
  { cn: '私人', name: 'private' },
  { cn: '特供', name: 'special' },
  { cn: '绑定', name: 'bind' },
  { cn: '未绑', name: 'unbind' },
  { cn: '熏陶', name: 'edify' },
  { cn: '编码中', name: 'tagging' },
  { cn: '未编码', name: 'untagged' },
  { cn: '喜马拉雅', name: 'xmly' },
  { cn: '本牛', name: 'benew' },
  { cn: '云盘', name: 'web' },
  { cn: '手机录音', name: 'app' },
  { cn: '库克音乐', name: 'kuke' },
  { cn: '其它', name: 'beeba' },
  { cn: '常青藤', name: 'ivydad' },
  { cn: '常青藤收费', name: 'ivydadSale' },
  { cn: '优贝', name: 'yourbay' },
  { cn: '工爸', name: 'idady' },
  { cn: '工爸收费', name: 'idadySale' },
  { cn: '虚拟', name: 'virtual' },
  { cn: '蜻蜓', name: 'qingting' },
  { cn: '蜻蜓收费', name: 'qingtingSale' },
  { cn: '蜻蜓单集收费', name: 'qingtingSingleSale' },
  { cn: '官方云盘', name: 'officialWeb' }
]

export const selectTranslate = {
  youzan: '有赞',
  all: '不限',
  back: '退货',
  change: '换货',
  repair: '维修',
  passed: '已完成',
  finished: '课程已结束',
  uncreated: '下周创建',
  paused: '已暂停',
  deviceEdify: '设备熏陶',
  deviceBattery: '电池拔电日志',
  batteryStatistic: '电池统计',
  chargeStatistic: '电池充电日志',
  workLog: '设备运行日志',
  deviceSheet: '设备听单',
  sheet: '听单',
  Ebbinghaus: '艾宾浩斯',
  SuperEbbinghaus: '艾宾浩斯增强版',
  Sequence: '线性',
  Psych: '心理成长',
  user: '主播',
  album: '专辑',
  track: '音频',
  redBoy: '小牛',
  device: '大牛',
  ntt001s: '增强版',
  ntt001c: '嘟嘟牛',
  ntt001w: '防水版',
  ntt001d: '猫牛',
  nttp1s: '增强小牛',
  nttr1: '绘本牛',
  redBoyIso: '小牛镜像',
  deviceIso: '大牛镜像',
  ntt001sIso: '增强版镜像',
  ntt001cIso: '嘟嘟牛镜像',
  ntt001wIso: '防水版镜像',
  ntt001dIso: '猫牛镜像',
  nttp1sIso: '增强小牛镜像',
  nttr1Iso: '绘本牛镜像',
  android: '安卓',
  iOs: '苹果',
  motherboard: '主板',
  product: '整机',
  release: 'Release',
  rc: 'RC',
  beta: 'Beta',
  alpha: 'Alpha',
  invalid: '无效',
  deviceTone: '大牛语音包',
  redBoyTone: '小牛语音包',
  ntt001sTone: '增强版语音包',
  ntt001cTone: '嘟嘟牛语音包',
  ntt001wTone: '防水版语音包',
  ntt001dTone: '猫牛语音包',
  nttp1sTone: '增强小牛语音包',
  nttr1Tone: '绘本牛语音包',
  text: '文本',
  aiJump: 'ai跳转',
  checking: '审核中',
  checked: '审核通过',
  denied: '审核未通过',
  spring: '春',
  summer: '夏',
  autumn: '秋',
  winter: '冬',
  punchCard: '小组',
  virtual: '虚拟',
  open: '公开',
  review: '审查中',
  pass: '已通过',
  reject: '已拒绝',
  revise: '修改中',
  mapGame: '成长地图',
  weChatPublicize: '公众号往期',
  publicize: '文章',
  file: '文件',
  dynamic: '动态',
  sharePoster: '分享海报',
  NO_PAY: '未付款',
  SUCCESS: '完成',
  PAY_FAIL: '支付失败',
  ALIPAY: '支付宝',
  WX: '微信',
  ALIWEBPAY: 'web支付宝',
  IAP: '苹果',
  POINT: '牛币'
}
